### ISSUE TITLE
[Game-Dev] CheckList

### ISSUE THREAD

**Issue by Underewarrr** [Underewarrr/pokemon-javascript-react-game#1]
Download And Setup
- [x] 1 - Download Tiled
- [x] 2 -  Import to project 
Tile Editor
- [x] Tile Layering for Ocean and Landmasses
- [x] Layering and placment of Trees
- [x] LandScape Details
- [x] Colision and Map bondaries
- [x] Foreground Layers
- [x] Export Layer for Project Import
:sparkles: **Player And Map Dev** :sparkles:
- [x] #2
- [x] #7 
- [x] #9 
- [ ] #18  
- [ ] Player-to-map-bondaries (Colision)
- [ ] Foreground Objects
- [ ] Player Movement animation
:sparkles: **Battle Sequence** :sparkles:
- [ ] Battle Activation
- [ ] Transiction from map to battle sequences
- [ ] DrawBattle Background
- [ ] Add Battle Sprites
